project wh_discursus {

    database_type: 'snowflake'

}

// CORE WAREHOUSE

table country_dim {

    country_pk varchar [pk]

    country_code varchar
    country_name varchar

}

table events_fct {

    event_pk varchar [pk]
    action_country_fk varchar [ref: - country_dim.country_pk]

    gdelt_event_natural_key int

    published_date date
    creation_ts timestamp

    source_url varchar
    action_geo_full_name varchar
    action_geo_adm1_code varchar
    action_geo_lat decimal
    action_geo_long decimal
    actor1_name varchar
    actor1_type1_code varchar
    actor2_name varchar
    actor2_type1_code varchar
    event_code varchar

    goldstein_scale decimal
    num_mentions int
    num_sources int
    num_articles int
    avg_tone decimal

}