# Dagster libraries to run both dagit and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.7-slim

# Environment variables
ENV DAGSTER_HOME=/opt/dagster/dagster_home/


RUN pip install \
    dagster \
    dagster-graphql \
    dagit \
    dagster-postgres \
    dagster-docker

# Copy dagster instance and workspace YAML
RUN mkdir -p $DAGSTER_HOME

COPY orchestration/dagster.yaml orchestration/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME