# Dagster libraries to run both dagit and the dagster-daemon. Does not
# need to have access to any pipeline code.

FROM python:3.9-slim

# Environment variables
ENV DAGSTER_HOME=/opt/dagster/dagster_home/


RUN pip install \
    dagster==1.0.6 \
    dagster-graphql==1.0.6 \
    dagit==1.0.6 \
    dagster-postgres==1.0.6 \
    dagster-docker==1.0.6

# Copy dagster instance and workspace YAML
RUN mkdir -p $DAGSTER_HOME

COPY dpf_core/dagster.yaml dpf_core/workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME