[tool.poetry]
name = "discursus-data-platform"
version = "0.1.0"
description = "The discursus project is an OSS social analytics data product that continuously delivers data on protest movements throughout North America."
authors = ["Olivier Dupuis <odupuis@lantrns.co>"]
license = "MIT"
packages = [{include = "discursus_data_platform"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
dbt-core = "1.3.2"
dbt-snowflake = "1.3.0"
dagster = "1.1.15"
dagit = "1.1.15"
dagster-graphql = "^1.1.15"
dagster-postgres = "0.17.15"
dagster-docker = "0.17.15"
dagster-shell = "0.17.15"
dagster-pandas = "0.17.15"
dagster-dbt = "0.17.15"
dagster-aws = "0.17.15"
dagster-snowflake = "0.17.15"
dagster-hex = "0.1.2"
sqlalchemy = "1.4.46"
pandas = "^1.5.2"
bs4 = "^0.0.1"
optparse-pretty = "^0.1.1"
boto3 = "^1.26.35"
fsspec = "^2022.11.0"
tweepy = "^4.12.1"
saf-aws = {git = "https://github.com/lantrns-analytics/saf_aws", rev = "release/0.2"}
saf-gdelt = {git = "https://github.com/lantrns-analytics/saf_gdelt", rev = "release/0.2"}
saf-novacene = {git = "https://github.com/discursus-data/saf_novacene.git", rev = "release/0.2.1"}
saf-web-scraper = {git = "https://github.com/lantrns-analytics/saf_web_scraper", rev = "release/0.2"}
future = "^0.18.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
