version: 2
models:
  - name: actors_dim
    columns:
      - name: actor_pk
        tests:
          - not_null
          - unique

  - name: events_actors_bridge
    columns:
      - name: event_actor_pk
        tests:
          - not_null
          - unique
      - name: event_fk
        tests:
          - not_null
          - relationships:
              to: ref('events_fct')
              field: event_pk
      - name: actor_fk
        tests:
          - not_null
          - relationships:
              to: ref('actors_dim')
              field: actor_pk

  - name: events_observations_bridge
    columns:
      - name: event_observation_pk
        tests:
          - not_null
          - unique
      - name: event_fk
        tests:
          - not_null
          - relationships:
              to: ref('events_fct')
              field: event_pk
      - name: observation_fk
        tests:
          - not_null
          - relationships:
              to: ref('observations_fct')
              field: observation_pk

  - name: events_fct
    columns:
      - name: event_pk
        tests:
          - not_null
          - unique
      - name: movement_fk
        tests:
          - not_null
          - relationships:
              to: ref('movements_dim')
              field: movement_pk

  - name: movements_dim
    columns:
      - name: movement_pk
        tests:
          - not_null
          - unique

  - name: observations_fct
    columns:
      - name: observation_pk
        tests:
          - not_null
          - unique
