project discursus
{ database_type: 'snowflake' }
table dbt_metrics_default_calendar      {
date_day date
date_year date
date_week date
date_quarter date
date_month date
}
table events_fct      {
event_pk varchar [pk]
movement_fk varchar [ref: - movements_dim.movement_pk]
action_geo_full_name varchar
action_geo_country_name varchar
action_geo_country_code varchar
action_geo_latitude numeric
action_geo_longitude numeric
event_date date
}
table movements_dim      {
movement_pk varchar [pk]
page_description_regex varchar
countries varchar
movement_name varchar
published_date_start date
published_date_end date
}
table observations_fct      {
observation_pk varchar [pk]
event_fk varchar [ref: - events_fct.event_pk]
observation_keywords varchar
observation_page_description varchar
observation_page_title varchar
observation_type varchar
observation_url varchar
published_date date
}
