version: 2

models:

  - name: int__actors
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - actor_name
            - actor_code
            - actor_geo_country_code