
name: 'discursus_dw'
version: '0.0.4'
require-dbt-version: ">=1.3.1"
config-version: 2

profile: discursus

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
docs-paths: ["wh_docs"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

seeds:
    discursus_dw:
        +schema: seed

        actor_types:
            +column_types:
                CODE: varchar(3)
                LABEL: varchar

        fips_country:
            +column_types:
                CODE: varchar(2)
                LABEL: varchar


models:
    discursus_dw:
        +persist_docs:
            relation: true
            columns: true
            
        staging:
            materialized: view
            schema: staging

        integration:
            materialized: view
            schema: integration
            
        warehouse:
            materialized: table


vars:
    surrogate_key_treat_nulls_as_empty_strings: true #turn on legacy behaviour