
name: 'discursus_dw'
version: '0.0.4'
require-dbt-version: ">=1.4.5"
config-version: 2

profile: discursus

model-paths: ["models"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

seeds:
    discursus_dw:
        +schema: seed

        fips_country:
            +column_types:
                CODE: varchar(2)
                LABEL: varchar


models:
    discursus_dw:
        +dagster_freshness_policy:
            maximum_lag_minutes: !!float 720
        +dagster_auto_materialize_policy: 
            type: lazy

        +persist_docs:
            relation: true
            columns: true
            
        staging:
            materialized: table
            schema: staging

        integration:
            materialized: table
            schema: integration
            
        warehouse:
            materialized: table


vars:
    surrogate_key_treat_nulls_as_empty_strings: true #turn on legacy behaviour