version: 2

models:
- name: stg__gdelt__events
  description: Source table for GDELT event

  columns:
  - name: gdelt_event_sk
    description: Unique source key
    tests:
    - unique
    - not_null
    - dbt_utils.at_least_one

- name: stg__gdelt__articles
  description: Source table for GDELT articles

  columns:
  - name: gdelt_gkg_article_id
    description: Unique source key
    tests:
    - unique:
        config:
          severity: error
          error_if: ">20"
          warn_if: ">10"
    - not_null
    - dbt_utils.at_least_one