version: 2

models:
- name: stg__seed__fips_countries
  description: Seed table of country reference table

  columns:
  - name: country_code
    description: FIPS code for country
    tests:
    - unique
    - not_null
    - dbt_utils.at_least_one

- name: stg__seed__actor_types
  description: Reference table for actor types

  columns:
  - name: actor_type_code
    description: CAMEO code for actor type
    tests:
    - unique
    - not_null
    - dbt_utils.at_least_one