version: 2

sources:
  - name: gdelt
    database: discursus_sources
    schema: public

    freshness:
      warn_after: {count: 1, period: day}
      error_after: {count: 2, period: day}

    tables:
      - name: gdelt_events
      - name: gdelt_mentions
      - name: gdelt_enhanced_mentions