export DIO_MINER_GDELT_HOME="/home/ec2-user/dio/miners/gdelt/"

export SNOWFLAKE_ACCOUNT="VALUE"
export SNOWFLAKE_USER="VALUE"
export SNOWFLAKE_PASSWORD="VALUE"
export SNOWFLAKE_ROLE="VALUE"

export SNOWFLAKE_LOAD_WAREHOUSE="VALUE"
export SNOWFLAKE_LOAD_DATABASE="VALUE"
export SNOWFLAKE_LOAD_SCHEMA="VALUE"

export SNOWFLAKE_DW_WAREHOUSE="VALUE"
export SNOWFLAKE_DW_DATABASE="VALUE"
export SNOWFLAKE_DW_SCHEMA="VALUE"