
name: 'discursus_dw'
version: '0.0.2'
require-dbt-version: "0.20.1"
config-version: 2

profile: discursus

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

seeds:
    discursus_dw:
        +schema: seed

        actor_types:
            +column_types:
                CODE: varchar(3)
                LABEL: varchar

        event_types:
            +column_types:
                CODE: varchar
                LABEL: varchar

        fips_country:
            +column_types:
                CODE: varchar(2)
                LABEL: varchar


models:
    discursus_dw:
        staging:
            materialized: view
            schema: staging

        integration:
            materialized: view
            schema: integration
            
        warehouse:
            materialized: table