resources:
  novacene_client:
    config:
      host: 
        env: ML_HOST
      login: 
        env: ML_LOGIN
      password: 
        env: ML_PASSWORD
      ml_relevancy_classification_model_id:
        env: ML_RELEVANCY_CLASSIFICATION_MODEL_ID