
name: 'discursus_dw'
version: '0.0.1'
require-dbt-version: "0.19.1"
config-version: 2

profile: discursus

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

seeds:
    discursus_dw:
        actor_types:
            code: varchar(3)
            label: varchar
        event_types:
            code: varchar(4)
            label: varchar
        fips_country:
            code: varchar(2)
            label: varchar

models:
    discursus_dw:
        staging:
            materialized: view
            schema: staging
        integration:
            materialized: view
            schema: integration
        warehouse:
            materialized: table