
name: 'discursus_dw'
version: '0.0.1'
require-dbt-version: ">=0.19.0"
config-version: 2

profile: discursus

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
    discursus_dw:
        staging:
            materialized: view
            schema: staging
        integration:
            materialized: view
            schema: integration
        warehouse:
            materialized: table
        utils:
            materialized: table
            schema: logs
            enabled: false