table events_fct {
    event_pk varchar [pk]
    movement_fk varchar [ref: - movements_dim.movement_pk]
    event_date date
    action_geo_country_name varchar
    action_geo_full_name varchar
    action_geo_country_code varchar
    action_geo_longitude numeric
    action_geo_latitude numeric
    event_category varchar //To be added
    participants_estimate integer //To be added
    sentiment_score numeric //To be added
}

table movements_dim {
    movement_pk varchar [pk]
    movement_name varchar
    published_date_start date
    published_date_end date
    countries varchar
    page_description_regex varchar
    movement_cause varchar //To be added
    movement_demands varchar //To be added
}

table observations_fct {
    observation_pk varchar [pk]
    published_date date
    observation_type varchar
    observation_url varchar
    observation_page_title varchar
    observation_page_description varchar
    observation_keywords varchar
    news_source_bias varchar //To be added
    observation_summary text //To be added
}

table key_figures_dim { //To be added
    key_figure_pk varchar [pk]
    organization_fk varchar [ref: - organizations_dim.organization_pk]
    key_figure_name varchar
    key_figure_role varchar
}

table organizations_dim { //To be added
    organization_pk varchar [pk]
    organization_name varchar
    organization_type varchar
}

table events_observations_bridge {
    event_observation_pk varchar [pk]
    event_fk varchar [ref: - events_fct.event_pk]
    observation_fk varchar [ref: - observations_fct.observation_pk]
}

table movements_key_figures_bridge { //To be added
    movement_key_figure_pk varchar [pk]
    movement_fk varchar [ref: - movements_dim.movement_pk]
    key_figure_fk varchar [ref: - key_figures_dim.key_figure_pk]
}

table movements_organizations_bridge { //To be added
    movement_organization_pk varchar [pk]
    movement_fk varchar [ref: - movements_dim.movement_pk]
    organization_fk varchar [ref: - organizations_dim.organization_pk]
}

table events_key_figures_bridge { //To be added
    event_key_figure_pk varchar [pk]
    event_fk varchar [ref: - events_fct.event_pk]
    key_figure_fk varchar [ref: - key_figures_dim.key_figure_pk]
}

table events_organizations_bridge { //To be added
    event_organization_pk varchar [pk]
    event_fk varchar [ref: - events_fct.event_pk]
    organization_fk varchar [ref: - organizations_dim.organization_pk]
}