project discursus {
  database_type: 'Snowflake'
}

table events_fct [headercolor: #7DB9B6] {
    event_pk varchar [pk]
    movement_fk varchar [ref: - movements_dim.movement_pk]
    event_date date
    action_geo_full_name varchar
    action_geo_country_code varchar
    action_geo_country_name varchar
    action_geo_state_name varchar
    action_geo_city_name varchar
    action_geo_longitude numeric
    action_geo_latitude numeric
}

table movements_dim [headercolor: #E96479] {
    movement_pk varchar [pk]
    movement_name varchar
    published_date_start date
    published_date_end date
    countries varchar
    page_description_regex varchar
}

table observations_fct [headercolor: #7DB9B6] {
    observation_pk varchar [pk]
    published_date date
    observation_type varchar
    observation_url varchar
    observation_page_title varchar
    observation_page_description varchar
    observation_keywords varchar
    observation_summary text //To be added
}

table actors_dim [headercolor: #E96479] { //To be added
    actor_pk varchar [pk]
    actor_name varchar
}

table events_observations_bridge [headercolor: #4D455D] {
    event_observation_pk varchar [pk]
    event_fk varchar [ref: - events_fct.event_pk]
    observation_fk varchar [ref: - observations_fct.observation_pk]
}

table events_actors_bridge [headercolor: #4D455D] { //To be added
    event_actor_pk varchar [pk]
    event_fk varchar [ref: - events_fct.event_pk]
    actor_fk varchar [ref: - actors_dim.actor_pk]
}