project wh_discursus {

    database_type: 'snowflake'

}

// CORE WAREHOUSE

table actors_dim {

    actor_pk varchar [pk]
    actor_geo_country_fk varchar [ref: - countries_dim.country_pk]

    actor_code varchar
    actor_name varchar
    actor_geo_country_code varchar
    actor_type_code varchar

}

table countries_dim {

    country_pk varchar [pk]

    country_code varchar
    country_name varchar

}

table events_fct {

    event_pk varchar [pk]
    protest_sk varchar //Combination of fields to associate similar protest events together: action_country_fk + action_geo_adm1_code + actor_type_combo + event_type
    action_country_fk varchar [ref: - countries_dim.country_pk]
    actor1_fk varchar [ref: - actors_dim.actor_pk]
    actor2_fk varchar [ref: - actors_dim.actor_pk]

    gdelt_event_natural_key int

    published_date date
    creation_ts timestamp

    source_url varchar
    action_geo_full_name varchar
    action_geo_adm1_code varchar
    action_geo_latitude decimal
    action_geo_longitude decimal
    event_type varchar //change

    goldstein_scale decimal
    num_mentions int
    num_sources int
    num_articles int
    avg_tone decimal

}


// ARTIFACTS WAREHOUSE

table artifact_articles_fct {

    artifact_article_pk varchar [pk]
    event_fk varchar [ref: - events_fct.event_pk]

    gdelt_event_natural_key int
    article_url varchar

    page_name varchar
    file_name varchar
    page_title varchar
    page_description varchar
    keywords varchar

}