version: 2

models:

  - name: events_fct
    description: Table of events
    columns:
      - name: event_pk
        description: >
          Unique identifier for events
        tests:
          - unique
          - not_null
      - name: movement_fk
        tests:
          - relationships:
              to: ref('movements_dim')
              field: movement_pk

  - name: observations_fct
    description: Table of observations
    columns:
      - name: observation_pk
        description: >
          Unique identifier for observations
        tests:
          - unique
          - not_null
      - name: event_fk
        tests:
          - relationships:
              to: ref('events_fct')
              field: event_pk
  
  - name: movements_dim
    description: Table of movements
    columns:
      - name: movement_pk
        description: >
          Unique identifier for movements
        tests:
          - unique
          - not_null