version: 2

models:
- name: stg__gdelt__events
  description: Source table for GDELT event

  columns:
  - name: gdelt_event_natural_key
    description: Unique dw key
    tests:
    - unique
    - not_null
    - dbt_utils.at_least_one